language: node_js
node_js:
- 9.5.0
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
- provider: npm
  email: pierre.lepers@gmail.com
  api_key:
    secure: $NPM_TOKEN
  on:
    branch: master
    repo: plepers/nanogl-pf
- provider: npm
  email: pierre.lepers@gmail.com
  dry_run: true
  api_key: $NPM_TOKEN
  on:
    branch: develop
    repo: plepers/nanogl-pf
