language: node_js
node_js:
- '9.5.0'
env:
  global:
  - secure: BAQ1y0c6naMTk1DMo6kVJBMtlPPB3M+YrrFG4Q/N5R28gNwzHaNgduJscoBdEXXFP+XvdmLw3Fxfb+Qd499kNe9ww04qqUd5IAwVt+xhUgdaj6lYciRH5hOirG6MrgdTyzefSVn9Wfl/iQeD0Fpusg8UBGTls4rRh0cII1IqUR+rHvzOs/Bejh1cCxcAq76ClXaEzYrIuRn1Mo382k0cdJVj/fbrPH4h3Y4lO1iDbKlHjhV0oBDpoN5goBLaHebFje52rYQBouaoR0P6GVc25RoRTJcVfpLEaFPgUBHxchyLEWuaCFzgNUC4tmK6A4m3ugWCFs6veVGMV/pgsgvxpFcO9zvx2tny8hbXuQZypvww/QjI4A+8zYVgBpWONFJaP6DxhpX+G9fIrUQjqj4NltXoYLc9TnfA3OgpgFsv928DxRLIk9E39ktkQkqwxfrxdR8kulqq9P+cvPWR74KSzQYOxSgFA+s2vqYKCYV66WnoIMnbFPH8ewMDjnbXIL1kEUCzuvxBW6PC4PhMBT9HjFIdBQDLQYZm8U/8rTLFz8XfGx0iSokGoENh2a8uSymr4eqLe3H/lhkKDQYAfI2dnsblwW76p9ueAU+h7Dvmpu5QURe3/ubIEgNfggCiHVXLft8OUL1oWdQHuAbU9pjmvTMmfwdXWih64F/ojMPucOM=
  - secure: QCaE0YGQDW39xbh1TrjRo6loV9KRyU9BgJpd90QHHKQBZ438G0aG9ZNHeQQ3TQpC+3MKcF5Mvb2Jqsk8oztG3417vSUedk4dZ56peCziY0oJ6rxQhjBJW4Atg7Cnx952Fnn6hccacQzxjXBzUgN7c/LZ+Jnx5JYes+SNxdi0YTE8hGiJ2B7qUqjvvKJwrwxAVUWbRZshEYpF9GDpQrk8UFRua1S6t3qWHlJK1kCsh//RZB8mJeaWb2TQt3p483pzoRLRUF2w7Xz33yNsk6Z33xWvHPkOr0r07f9smwnqicAY0SF5ImyFtPqnawDr2fPFNStxhEJBwliIpFSNHdi4LspZJ5Im8b6/HpzzdeNvDfLFSx3xLk9p2cVemNw9cvqNdZEfxzgIlyuBqYx+lX0jKd6Ba+XjEZkX+AeIhWWEqJEwkv9L3pVId61c0RFAnJWsL7P8b4KFnLuYbJwAL77m6tZf+LlgX5swgweojqVUf5si8NfKJEteftCp4Q20tkISh6lMYmfVbrl7lIR3HMjlsk4hk55Sy4PqGQycV4yRUauJPmoiUe14NH85fv4lNNMteesNL1O+28r8l71so1Vh8WKUoe0q6SyKcD0Pxa3Ba+stYeWaTlB0+CWdGDQRjlcpzmcoDUBP5uladsq7zoFfJj+EzbSIBY74lXQdddw8wVc=
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  - provider: npm
    email: pierre.lepers@gmail.com
    api_key:
      secure: T4dDVu4RuFa26+gA06/NkXLraV+PvzHy9OCVPW4wksBi0f8uioO4tK+8XeNyn+AEBJn+JHkWg9yufiLhGroI6Re+J0lP0qFWLVTKYVY79TxEGAI9GUoCjiMoLftCVaUWI3JfwENC0JgPv/4jqM8i5s8BPCTL24QVggq/adJ0XkhgN2Ki15fAn9CycL94l92IdtD+CCIPA2R7VjVnghtmi2mmXh5/nRG99t8AWGYpC0p/KH+1ytSWx3UrJDBfIPuFpgmd0ivfuULw2oev5tGT0AgtJ9fD1ApFen84XqqkeVXymmz+AkTEg2zjooLqSjsm3lBpNhYG9pVovseCeuvYOcXl4+J+dLjaBCHH3mZabLlotrjzuVv8q8oALn7bBcl60EbCJyN3JrQJWK+UoLgy/W7GY4keV7Br9248Sh+otCVmwGZFRfAKn3XR5xndH0VilwqhEal9qkGBKY4gxC2SNIInrSlMNDk2viimyvwJyVMVZg5o0O/qnMbeA9R0yEpnfsrm++8odvBh7tzDPqpZK4UDReJEQ4f8cIEtl9HnSKD+j2kuV74TI253QSWThm4Ai0HhTTOyuV6B3Yd9Bk4OvzVThGdJO0cby+OATMXjbeVnhj/Ed7iydgJ5c4o+skc15Hn5A75o4n3dkkhJ2OvVcn4DY8yG9X9VPBLaqK4LlSE=
    on:
      branch: master
      repo: plepers/nanogl-pf
  - provider: npm
    email: pierre.lepers@gmail.com
    dry_run: true
    api_key:
      secure: T4dDVu4RuFa26+gA06/NkXLraV+PvzHy9OCVPW4wksBi0f8uioO4tK+8XeNyn+AEBJn+JHkWg9yufiLhGroI6Re+J0lP0qFWLVTKYVY79TxEGAI9GUoCjiMoLftCVaUWI3JfwENC0JgPv/4jqM8i5s8BPCTL24QVggq/adJ0XkhgN2Ki15fAn9CycL94l92IdtD+CCIPA2R7VjVnghtmi2mmXh5/nRG99t8AWGYpC0p/KH+1ytSWx3UrJDBfIPuFpgmd0ivfuULw2oev5tGT0AgtJ9fD1ApFen84XqqkeVXymmz+AkTEg2zjooLqSjsm3lBpNhYG9pVovseCeuvYOcXl4+J+dLjaBCHH3mZabLlotrjzuVv8q8oALn7bBcl60EbCJyN3JrQJWK+UoLgy/W7GY4keV7Br9248Sh+otCVmwGZFRfAKn3XR5xndH0VilwqhEal9qkGBKY4gxC2SNIInrSlMNDk2viimyvwJyVMVZg5o0O/qnMbeA9R0yEpnfsrm++8odvBh7tzDPqpZK4UDReJEQ4f8cIEtl9HnSKD+j2kuV74TI253QSWThm4Ai0HhTTOyuV6B3Yd9Bk4OvzVThGdJO0cby+OATMXjbeVnhj/Ed7iydgJ5c4o+skc15Hn5A75o4n3dkkhJ2OvVcn4DY8yG9X9VPBLaqK4LlSE=
    on:
      branch: develop
      repo: plepers/nanogl-pf
