language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: BAQ1y0c6naMTk1DMo6kVJBMtlPPB3M+YrrFG4Q/N5R28gNwzHaNgduJscoBdEXXFP+XvdmLw3Fxfb+Qd499kNe9ww04qqUd5IAwVt+xhUgdaj6lYciRH5hOirG6MrgdTyzefSVn9Wfl/iQeD0Fpusg8UBGTls4rRh0cII1IqUR+rHvzOs/Bejh1cCxcAq76ClXaEzYrIuRn1Mo382k0cdJVj/fbrPH4h3Y4lO1iDbKlHjhV0oBDpoN5goBLaHebFje52rYQBouaoR0P6GVc25RoRTJcVfpLEaFPgUBHxchyLEWuaCFzgNUC4tmK6A4m3ugWCFs6veVGMV/pgsgvxpFcO9zvx2tny8hbXuQZypvww/QjI4A+8zYVgBpWONFJaP6DxhpX+G9fIrUQjqj4NltXoYLc9TnfA3OgpgFsv928DxRLIk9E39ktkQkqwxfrxdR8kulqq9P+cvPWR74KSzQYOxSgFA+s2vqYKCYV66WnoIMnbFPH8ewMDjnbXIL1kEUCzuvxBW6PC4PhMBT9HjFIdBQDLQYZm8U/8rTLFz8XfGx0iSokGoENh2a8uSymr4eqLe3H/lhkKDQYAfI2dnsblwW76p9ueAU+h7Dvmpu5QURe3/ubIEgNfggCiHVXLft8OUL1oWdQHuAbU9pjmvTMmfwdXWih64F/ojMPucOM=
  - secure: QCaE0YGQDW39xbh1TrjRo6loV9KRyU9BgJpd90QHHKQBZ438G0aG9ZNHeQQ3TQpC+3MKcF5Mvb2Jqsk8oztG3417vSUedk4dZ56peCziY0oJ6rxQhjBJW4Atg7Cnx952Fnn6hccacQzxjXBzUgN7c/LZ+Jnx5JYes+SNxdi0YTE8hGiJ2B7qUqjvvKJwrwxAVUWbRZshEYpF9GDpQrk8UFRua1S6t3qWHlJK1kCsh//RZB8mJeaWb2TQt3p483pzoRLRUF2w7Xz33yNsk6Z33xWvHPkOr0r07f9smwnqicAY0SF5ImyFtPqnawDr2fPFNStxhEJBwliIpFSNHdi4LspZJ5Im8b6/HpzzdeNvDfLFSx3xLk9p2cVemNw9cvqNdZEfxzgIlyuBqYx+lX0jKd6Ba+XjEZkX+AeIhWWEqJEwkv9L3pVId61c0RFAnJWsL7P8b4KFnLuYbJwAL77m6tZf+LlgX5swgweojqVUf5si8NfKJEteftCp4Q20tkISh6lMYmfVbrl7lIR3HMjlsk4hk55Sy4PqGQycV4yRUauJPmoiUe14NH85fv4lNNMteesNL1O+28r8l71so1Vh8WKUoe0q6SyKcD0Pxa3Ba+stYeWaTlB0+CWdGDQRjlcpzmcoDUBP5uladsq7zoFfJj+EzbSIBY74lXQdddw8wVc=
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: O8PGYM7jNKb8gHL7YjZu4XLrU18A8/iO3cXPWjsh8Un2/ro7I3XJKrs7ROMCChVany6MUFiFp26Li3OYlfjGwJeTHIA/RFZS8cnLXqbmr1EozsvZChi+OSm6vd/xbUHs0anIIRFcaguA9HqFttThtbBgKSvytKDjm4Wav21mdHidA+YNxaRC2EoR6Sw8CcdQHiNbKMWeXTbAHy1BC10Zd4lo410mBidvGnDDNXMEuHXGLBfhTmoQbWTqTFrwJ7kV3oxBVobjaUcXPgwDwsKKUO1WF8LF5el1cxFz8asfQtdHLfM51Vwb9pjhfcZ8LnAhPivvt4agv4VCUCtZoDJR3kSFpD1qaVTPqYccu4hRrpHWfAcLxyOY3SmYDDaPX+BJ9egTo89eC1HgiGOdDez9A8usEaAvvdvfxvv6Ux21rkqtGExJYKZlLqvIh32+Xx9DhjDIWvEcCgOui2Nlz2I/f/Z2pMwO2qMV03cBxPJlWHRnP/ePQVRG/P3w/qSCjsiL+YTls7m2IriebZXtDecs1CZXTmQHV0Ged7lbw+IgQ9B9KLcgb6mugsNUEtmbSMy+cFaWrMi+fBuAa4neGcn9ljPKG6/iAiknDtvW5/gemMQuzs1q5gcpXffjosueVPX19b+W8lFXFMtidvlPBNScNFKNoVsoobO9Nj04Px2gUhk=
  on:
    branch: master
    repo: plepers/nanogl-pf
